//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductManagementSystemData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Brand1
    {
        public int SalesInvoiceID { get; set; }
        public double ShippingCharges { get; set; }
        public double CashDisc { get; set; }
        public string InvoiceType { get; set; }
        public string CustomerDetail1 { get; set; }
        public int CustomerID { get; set; }
        public string PreFix { get; set; }
        public string InvoiceCode { get; set; }
        public string InvoiceCode1 { get; set; }
        public Nullable<System.DateTime> InvoiceDate1 { get; set; }
        public string InvoiceDate { get; set; }
        public string PartyName { get; set; }
        public string StateSaleTax { get; set; }
        public Nullable<double> GrossTotal { get; set; }
        public Nullable<double> TAXFree { get; set; }
        public Nullable<double> TAXable4 { get; set; }
        public Nullable<double> VAT4 { get; set; }
        public Nullable<double> VAT1 { get; set; }
        public Nullable<double> TAXable12_5 { get; set; }
        public Nullable<double> VAT12_5 { get; set; }
        public Nullable<double> VAT2_5 { get; set; }
        public Nullable<int> ItemID { get; set; }
    }
}
