//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductManagementSystemData
{
    using System;
    using System.Collections.Generic;
    
    public partial class myTransaction
    {
        public int RecordID { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
        public string TransType { get; set; }
        public Nullable<int> TransID { get; set; }
        public double TransQty { get; set; }
        public Nullable<double> TransRate { get; set; }
        public Nullable<int> Location { get; set; }
        public Nullable<int> ItemID { get; set; }
        public Nullable<int> ReferenceID { get; set; }
    }
}
