//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductManagementSystemData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReferenceTypeMaster
    {
        public int ReferenceTypeID { get; set; }
        public string ReferenceType { get; set; }
        public string Prefix { get; set; }
    }
}
