//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductManagementSystemData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_GiftVoucherDetails
    {
        public int GVDetailId { get; set; }
        public Nullable<int> BatchID { get; set; }
        public string VoucherCode { get; set; }
        public decimal Amount { get; set; }
        public string PartyName { get; set; }
        public Nullable<int> InvoiceNo { get; set; }
        public Nullable<int> IsSold { get; set; }
        public Nullable<System.DateTime> SoldDate { get; set; }
        public Nullable<int> IsReedim { get; set; }
        public Nullable<System.DateTime> ReedimDate { get; set; }
        public Nullable<int> IssueID { get; set; }
        public Nullable<decimal> ReedimAmount { get; set; }
        public Nullable<int> InsertBy { get; set; }
        public Nullable<System.DateTime> InsertAt { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public Nullable<bool> IsCancel { get; set; }
    }
}
