//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductManagementSystemData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_TermsMaster
    {
        public tb_TermsMaster()
        {
            this.tb_GiftVoucherTermsandConditions = new HashSet<tb_GiftVoucherTermsandConditions>();
        }
    
        public int TermId { get; set; }
        public string Description { get; set; }
        public Nullable<int> InsertBy { get; set; }
        public Nullable<System.DateTime> InsertAt { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
    
        public virtual ICollection<tb_GiftVoucherTermsandConditions> tb_GiftVoucherTermsandConditions { get; set; }
    }
}
