//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductManagementSystemData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_UpdateTransactionType
    {
        public int TranTypeID { get; set; }
        public Nullable<int> TransactionType { get; set; }
        public Nullable<int> UpdateLogID { get; set; }
    }
}
