//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductManagementSystemData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAddress
    {
        public int AddressID { get; set; }
        public Nullable<int> AddressType { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Area { get; set; }
        public Nullable<int> Country { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public string Zip { get; set; }
        public Nullable<int> PartyID { get; set; }
        public Nullable<int> AddressIndex { get; set; }
        public Nullable<int> MpduleID { get; set; }
        public Nullable<bool> IsDefault { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> StateID { get; set; }
    }
}
