//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductManagementSystemData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCrditNoteToLedgerItem
    {
        public tblCrditNoteToLedgerItem()
        {
            this.tblCreditItemsToDiscounts = new HashSet<tblCreditItemsToDiscount>();
            this.tblCreditNoteItemsToTaxes = new HashSet<tblCreditNoteItemsToTax>();
        }
    
        public int RecordID { get; set; }
        public Nullable<int> CrditNoteToLEdgerID { get; set; }
        public Nullable<int> ItemID { get; set; }
        public Nullable<double> ActualQty { get; set; }
        public Nullable<double> BilledQty { get; set; }
        public Nullable<int> Unit { get; set; }
        public Nullable<double> Rate { get; set; }
        public Nullable<double> MRP { get; set; }
        public string Remark { get; set; }
        public Nullable<int> OutwardRef { get; set; }
        public Nullable<int> GodownID { get; set; }
        public string Batchno { get; set; }
        public Nullable<int> SIRefNo { get; set; }
        public Nullable<int> RejectionInId { get; set; }
        public Nullable<System.DateTime> MfgDate { get; set; }
        public Nullable<System.DateTime> ExpDate { get; set; }
    
        public virtual tblCrditNoteToLedger tblCrditNoteToLedger { get; set; }
        public virtual ICollection<tblCreditItemsToDiscount> tblCreditItemsToDiscounts { get; set; }
        public virtual ICollection<tblCreditNoteItemsToTax> tblCreditNoteItemsToTaxes { get; set; }
    }
}
