//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductManagementSystemData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCustomerBrandDisc
    {
        public int RecordId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> BrandId { get; set; }
        public Nullable<double> DiscountPerecentage { get; set; }
    }
}
