//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductManagementSystemData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCompanyMaster
    {
        public int CompanyID { get; set; }
        public string CompanyName { get; set; }
        public string EmailAddress { get; set; }
        public string LocalSalesTaxNumber { get; set; }
        public string InterStateSalesTaxNumber { get; set; }
        public string IncomeTaxNumber { get; set; }
        public string CurrencySymbol { get; set; }
        public Nullable<bool> MaintainInventory { get; set; }
        public string FinancialYearFrom { get; set; }
        public Nullable<System.DateTime> BooksBeginningFrom { get; set; }
        public string LogoFileExtension { get; set; }
        public Nullable<int> OwnerUserID { get; set; }
        public Nullable<int> InsertBy { get; set; }
        public Nullable<System.DateTime> InsertAt { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string Phone3 { get; set; }
        public string MobileNo { get; set; }
        public string WebSite { get; set; }
    }
}
