//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductManagementSystemData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCreditNoteItem
    {
        public tblCreditNoteItem()
        {
            this.tblCreditNoteItemDiscounts = new HashSet<tblCreditNoteItemDiscount>();
        }
    
        public int CRDItemID { get; set; }
        public Nullable<int> CreidtNoteID { get; set; }
        public Nullable<int> ItemID { get; set; }
        public Nullable<int> ReferenceID { get; set; }
        public Nullable<int> ReferenceType { get; set; }
        public Nullable<double> Qty { get; set; }
        public Nullable<int> Unit { get; set; }
        public Nullable<double> MRP { get; set; }
        public string TaxDescription { get; set; }
        public Nullable<System.DateTime> MfgDate { get; set; }
        public Nullable<System.DateTime> ExpDate { get; set; }
        public string Remark { get; set; }
        public Nullable<int> TaxProfileID { get; set; }
        public Nullable<int> GodownId { get; set; }
        public Nullable<double> Rate { get; set; }
        public Nullable<double> OGSPerValue { get; set; }
    
        public virtual ICollection<tblCreditNoteItemDiscount> tblCreditNoteItemDiscounts { get; set; }
    }
}
