//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductManagementSystemData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCrditNoteToLedger
    {
        public tblCrditNoteToLedger()
        {
            this.tblCrditNoteToLedgerItems = new HashSet<tblCrditNoteToLedgerItem>();
            this.tblCreditNoteToDiscounts = new HashSet<tblCreditNoteToDiscount>();
            this.tblCreditNoteToTaxes = new HashSet<tblCreditNoteToTax>();
        }
    
        public int RecordID { get; set; }
        public Nullable<int> CrditNoteID { get; set; }
        public Nullable<int> LedgerID { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<int> IsCrdit { get; set; }
        public string Remark { get; set; }
    
        public virtual tblParty_Master tblParty_Master { get; set; }
        public virtual ICollection<tblCrditNoteToLedgerItem> tblCrditNoteToLedgerItems { get; set; }
        public virtual ICollection<tblCreditNoteToDiscount> tblCreditNoteToDiscounts { get; set; }
        public virtual ICollection<tblCreditNoteToTax> tblCreditNoteToTaxes { get; set; }
    }
}
