//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductManagementSystemData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCompanyGroup
    {
        public tblCompanyGroup()
        {
            this.tblParty_Master = new HashSet<tblParty_Master>();
        }
    
        public int GroupID { get; set; }
        public Nullable<int> DefaultGroupID { get; set; }
        public string GroupName { get; set; }
        public Nullable<int> NatureID { get; set; }
        public Nullable<bool> BahaveAsSubGroup { get; set; }
        public Nullable<bool> IsPrimary { get; set; }
        public Nullable<int> ParentGroupID { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<bool> AffectProfitLossAccount { get; set; }
        public Nullable<bool> IsDefault { get; set; }
        public Nullable<int> InsertBy { get; set; }
        public Nullable<System.DateTime> InsertAt { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
    
        public virtual ICollection<tblParty_Master> tblParty_Master { get; set; }
    }
}
