//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductManagementSystemData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblcountrystate_tbl
    {
        public int stateid { get; set; }
        public string State { get; set; }
        public string Statecode { get; set; }
        public string countrycode { get; set; }
    }
}
