//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductManagementSystemData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDebitNoteItem
    {
        public int DebitNoteItemID { get; set; }
        public Nullable<int> DebitNoteID { get; set; }
        public Nullable<int> ItemID { get; set; }
        public Nullable<double> ActualQty { get; set; }
        public Nullable<double> BilledQty { get; set; }
        public Nullable<int> ReferenceID { get; set; }
        public Nullable<int> ReferenceType { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<int> Unit { get; set; }
        public Nullable<double> Rate { get; set; }
        public Nullable<double> MRP { get; set; }
        public string TaxDescription { get; set; }
        public Nullable<System.DateTime> MfgDate { get; set; }
        public Nullable<System.DateTime> ExpDate { get; set; }
        public string Remark { get; set; }
        public Nullable<int> GodownID { get; set; }
        public string Batchno { get; set; }
        public Nullable<int> TaxProfileID { get; set; }
        public Nullable<double> OGSPerValue { get; set; }
    }
}
