//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductManagementSystemData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDiscountTypeMaster
    {
        public tblDiscountTypeMaster()
        {
            this.tblSalesInvoiceItemToDiscounts = new HashSet<tblSalesInvoiceItemToDiscount>();
        }
    
        public int DiscountID { get; set; }
        public string DiscountName { get; set; }
        public Nullable<int> LedgerType { get; set; }
        public Nullable<bool> DiscountType { get; set; }
        public Nullable<decimal> DiscountValue { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> InsertBy { get; set; }
        public Nullable<System.DateTime> InsertAt { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
    
        public virtual ICollection<tblSalesInvoiceItemToDiscount> tblSalesInvoiceItemToDiscounts { get; set; }
    }
}
