//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductManagementSystemData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDefaultLedger
    {
        public int LegerID { get; set; }
        public string LedgerName { get; set; }
        public Nullable<int> LegerGroup { get; set; }
        public Nullable<bool> MaintainInventory { get; set; }
        public Nullable<bool> OpeningBalance { get; set; }
    }
}
