//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductManagementSystemData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDefaultGroup
    {
        public int GroupID { get; set; }
        public string GroupName { get; set; }
        public Nullable<int> NatureID { get; set; }
        public Nullable<bool> BahaveAsSubGroup { get; set; }
        public Nullable<bool> IsPrimary { get; set; }
        public Nullable<int> ParentGroupID { get; set; }
    }
}
