//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductManagementSystemData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFPInvoiceStatu
    {
        public int RecordID { get; set; }
        public Nullable<int> FPInvoiceStatusID { get; set; }
        public string FPInvoiceStatus { get; set; }
        public Nullable<int> FPInvoiceStatusType { get; set; }
    }
}
