//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductManagementSystemData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGiftVoucherMaster
    {
        public int BatchID { get; set; }
        public string BatchNo { get; set; }
        public int NoOfVoucher { get; set; }
        public decimal Amount { get; set; }
        public Nullable<int> ExtensionID { get; set; }
        public string StartingVoucherCode { get; set; }
        public string EndingVoucherCode { get; set; }
        public Nullable<System.DateTime> ValidityFrom { get; set; }
        public Nullable<System.DateTime> ValidityTo { get; set; }
        public int ValidityDays { get; set; }
        public Nullable<int> InsertBy { get; set; }
        public Nullable<System.DateTime> InsertAt { get; set; }
        public int UpdateBy { get; set; }
        public System.DateTime UpdateAt { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<System.DateTime> VouherGenrationDate { get; set; }
    }
}
