//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductManagementSystemData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGiftVoucherIssue
    {
        public int IssueID { get; set; }
        public string IssueCode { get; set; }
        public string IssueBy { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public string IssueTo { get; set; }
        public string DedicateTo { get; set; }
        public Nullable<int> InsertBy { get; set; }
        public Nullable<System.DateTime> InsertAt { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public Nullable<int> StoreID { get; set; }
        public Nullable<int> PaidByPartyID { get; set; }
    }
}
