//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductManagementSystemData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInventoryVoucher
    {
        public int TransactionId { get; set; }
        public Nullable<int> PartyID { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public string TransactionDetail { get; set; }
        public string TransactionCode { get; set; }
        public string DeliveredBy { get; set; }
        public string ReceivedBy { get; set; }
    }
}
