//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductManagementSystemData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblItemListForSyncronize
    {
        public int RecordID { get; set; }
        public Nullable<int> InvoiceID { get; set; }
        public string TransType { get; set; }
        public Nullable<int> ItemID { get; set; }
        public Nullable<System.DateTime> EnteredDate { get; set; }
        public Nullable<bool> IsSynced { get; set; }
    }
}
