//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductManagementSystemData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblItemMaster
    {
        public tblItemMaster()
        {
            this.tblItemToOtherExpenses = new HashSet<tblItemToOtherExpens>();
            this.tblItemToSubItems = new HashSet<tblItemToSubItem>();
            this.tblItemWiseUnitConversions = new HashSet<tblItemWiseUnitConversion>();
            this.tblSalesInvoiceItems = new HashSet<tblSalesInvoiceItem>();
        }
    
        public int RecordID { get; set; }
        public string ItemName { get; set; }
        public string ItemCode { get; set; }
        public string Specification { get; set; }
        public string Identifier { get; set; }
        public Nullable<double> DefaultPrice { get; set; }
        public Nullable<double> MRP { get; set; }
        public Nullable<int> ItemTypeID { get; set; }
        public Nullable<bool> MaintainGodown { get; set; }
        public Nullable<bool> MaintainBatchwise { get; set; }
        public Nullable<bool> MaintainMfgDate { get; set; }
        public Nullable<bool> MaintainExpDate { get; set; }
        public Nullable<double> ItemLossPercentage { get; set; }
        public Nullable<int> DefaultUnit { get; set; }
        public Nullable<double> ReorderLevel { get; set; }
        public Nullable<int> MaximumStock { get; set; }
        public Nullable<int> MinimumStock { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> InsertBy { get; set; }
        public Nullable<System.DateTime> InsertAt { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public Nullable<int> TaxProfileID { get; set; }
        public Nullable<int> BrandID { get; set; }
        public string Auther { get; set; }
        public string ItemTag { get; set; }
        public string AgeGroup { get; set; }
        public string BrandName { get; set; }
        public Nullable<int> StoreQty { get; set; }
        public string Distributor { get; set; }
        public string Distributor1 { get; set; }
        public string ItemName1 { get; set; }
        public string DisplayText { get; set; }
        public string ReasonForEdit { get; set; }
    
        public virtual tblItemCategoryMaster tblItemCategoryMaster { get; set; }
        public virtual ICollection<tblItemToOtherExpens> tblItemToOtherExpenses { get; set; }
        public virtual ICollection<tblItemToSubItem> tblItemToSubItems { get; set; }
        public virtual ICollection<tblItemWiseUnitConversion> tblItemWiseUnitConversions { get; set; }
        public virtual ICollection<tblSalesInvoiceItem> tblSalesInvoiceItems { get; set; }
    }
}
