//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductManagementSystemData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInword
    {
        public tblInword()
        {
            this.tblInwordItems = new HashSet<tblInwordItem>();
            this.tblInwordToDiscounts = new HashSet<tblInwordToDiscount>();
            this.tblInwordToPORefs = new HashSet<tblInwordToPORef>();
            this.tblInwordToTAXes = new HashSet<tblInwordToTAX>();
        }
    
        public int InwordID { get; set; }
        public Nullable<System.DateTime> InwordDate { get; set; }
        public string InwordCode { get; set; }
        public string InwordCodeFromSupplier { get; set; }
        public string Subject { get; set; }
        public Nullable<int> PartyID { get; set; }
        public Nullable<int> PORefNo { get; set; }
        public string SupplierDetail { get; set; }
        public string RecieverDetail { get; set; }
        public Nullable<int> TransportCompany { get; set; }
        public Nullable<int> TransportType { get; set; }
        public string DocNo { get; set; }
        public string PortOfLoading { get; set; }
        public string PortOfDischarge { get; set; }
        public string CountryFrom { get; set; }
        public Nullable<int> InsertBy { get; set; }
        public Nullable<System.DateTime> InsertAt { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public Nullable<double> total { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<double> RoundOff { get; set; }
        public Nullable<int> TaxType { get; set; }
        public Nullable<double> CSTPerValue { get; set; }
        public Nullable<double> CashDisc { get; set; }
        public Nullable<int> GodownID { get; set; }
        public string ReasonForEdit { get; set; }
        public Nullable<int> StateID { get; set; }
        public Nullable<int> TaxProfileCategoryID { get; set; }
        public Nullable<bool> IsTaxInclusive { get; set; }
        public Nullable<int> StoreID { get; set; }
        public Nullable<double> SumOfCostRate { get; set; }
        public string mStatus { get; set; }
    
        public virtual ICollection<tblInwordItem> tblInwordItems { get; set; }
        public virtual ICollection<tblInwordToDiscount> tblInwordToDiscounts { get; set; }
        public virtual ICollection<tblInwordToPORef> tblInwordToPORefs { get; set; }
        public virtual ICollection<tblInwordToTAX> tblInwordToTAXes { get; set; }
    }
}
