//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductManagementSystemData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblItemGridColumnPermission
    {
        public int RecordID { get; set; }
        public Nullable<int> PageID { get; set; }
        public Nullable<bool> ApplyAllDisc { get; set; }
        public Nullable<bool> Barcode { get; set; }
        public Nullable<bool> ItemName { get; set; }
        public Nullable<bool> SOC { get; set; }
        public Nullable<bool> Reference { get; set; }
        public Nullable<bool> Quantity { get; set; }
        public Nullable<bool> Unit { get; set; }
        public Nullable<bool> Rate { get; set; }
        public Nullable<bool> MRP { get; set; }
        public Nullable<bool> Disc { get; set; }
        public Nullable<bool> AfterDisc { get; set; }
        public Nullable<bool> Vat { get; set; }
        public Nullable<bool> PurchaseVat { get; set; }
    }
}
