//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductManagementSystemData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblItemWiseUnitConversion
    {
        public int RecordID { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> ItemID { get; set; }
        public Nullable<int> UnitName1 { get; set; }
        public Nullable<int> UnitName2 { get; set; }
        public Nullable<double> OffSet { get; set; }
    
        public virtual tblItemMaster tblItemMaster { get; set; }
    }
}
