//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductManagementSystemData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblJournalVoucherToLedgerItem
    {
        public tblJournalVoucherToLedgerItem()
        {
            this.tblJournalVoucherItemsToDiscounts = new HashSet<tblJournalVoucherItemsToDiscount>();
            this.tblJournalVoucherItemsToTaxes = new HashSet<tblJournalVoucherItemsToTax>();
        }
    
        public int RecordID { get; set; }
        public Nullable<int> JVToLEdgerID { get; set; }
        public Nullable<int> ItemID { get; set; }
        public Nullable<double> ActualQty { get; set; }
        public Nullable<double> BilledQty { get; set; }
        public Nullable<int> Unit { get; set; }
        public Nullable<double> Rate { get; set; }
        public string Remark { get; set; }
        public Nullable<int> InwardRef { get; set; }
        public Nullable<int> GodownID { get; set; }
        public string Batchno { get; set; }
        public Nullable<int> PORefNo { get; set; }
        public Nullable<int> InwordRefNo { get; set; }
        public Nullable<System.DateTime> MfgDate { get; set; }
        public Nullable<System.DateTime> ExpDate { get; set; }
    
        public virtual ICollection<tblJournalVoucherItemsToDiscount> tblJournalVoucherItemsToDiscounts { get; set; }
        public virtual ICollection<tblJournalVoucherItemsToTax> tblJournalVoucherItemsToTaxes { get; set; }
        public virtual tblJVToLedger tblJVToLedger { get; set; }
    }
}
