//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductManagementSystemData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblJVToLedger
    {
        public tblJVToLedger()
        {
            this.tblJournalVoucherToLedgerItems = new HashSet<tblJournalVoucherToLedgerItem>();
        }
    
        public int RecordID { get; set; }
        public Nullable<int> JvID { get; set; }
        public Nullable<int> LedgerID { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<bool> IsCrdit { get; set; }
        public string Remark { get; set; }
    
        public virtual tblJournalVoucher tblJournalVoucher { get; set; }
        public virtual ICollection<tblJournalVoucherToLedgerItem> tblJournalVoucherToLedgerItems { get; set; }
    }
}
