//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductManagementSystemData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLog
    {
        public int LogID { get; set; }
        public int SectionID { get; set; }
        public int FunctionID { get; set; }
        public int ActivityType { get; set; }
        public int UserID { get; set; }
        public System.DateTime LogTime { get; set; }
        public string AfterLogData { get; set; }
        public int TransID { get; set; }
        public string Remark1 { get; set; }
        public string Remark2 { get; set; }
        public string BeforeLogData { get; set; }
        public int ModuleID { get; set; }
        public Nullable<int> MenuID { get; set; }
        public string Controller { get; set; }
        public string Action { get; set; }
        public Nullable<int> LogDataTypeID { get; set; }
        public string LogDataType { get; set; }
    }
}
