//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductManagementSystemData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblModuleMaster
    {
        public tblModuleMaster()
        {
            this.tblSectionMasters = new HashSet<tblSectionMaster>();
        }
    
        public int ModuleId { get; set; }
        public string ModuleName { get; set; }
        public string ModuleDiscription { get; set; }
        public string Url { get; set; }
    
        public virtual ICollection<tblSectionMaster> tblSectionMasters { get; set; }
    }
}
