//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductManagementSystemData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNegativeStockNotification
    {
        public long NotificationId { get; set; }
        public int UserId { get; set; }
        public int ItemId { get; set; }
        public double Stock { get; set; }
        public Nullable<int> UnitId { get; set; }
        public long SalesInvoiceId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> Aprove { get; set; }
        public string AprovalRemark { get; set; }
        public string AprovedBy { get; set; }
        public string UserName { get; set; }
    }
}
