//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductManagementSystemData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOnlineSKUMapping
    {
        public int RecordID { get; set; }
        public Nullable<long> OnlineCompanyID { get; set; }
        public string OnlineCompanySKU { get; set; }
        public string OnlineCompanyName2 { get; set; }
        public string OnlineCompanyName { get; set; }
        public Nullable<long> LocalID { get; set; }
        public string Remark { get; set; }
    }
}
