//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductManagementSystemData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOutword_6THFloorremove
    {
        public int OutwordID { get; set; }
        public Nullable<System.DateTime> OutwordDate { get; set; }
        public string OutwordCode { get; set; }
        public string Subject { get; set; }
        public Nullable<int> PartyID { get; set; }
        public Nullable<int> SORefNo { get; set; }
        public string SupplierDetail { get; set; }
        public string RecieverDetail { get; set; }
        public Nullable<int> TransportCompany { get; set; }
        public Nullable<int> TransportType { get; set; }
        public string DocNo { get; set; }
        public string PortOfLoading { get; set; }
        public string PortOfDischarge { get; set; }
        public string CountryFrom { get; set; }
        public Nullable<int> InsertBy { get; set; }
        public Nullable<System.DateTime> InsertAt { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public Nullable<double> total { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<double> RoundOff { get; set; }
    }
}
