//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductManagementSystemData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOnlineSalesInvoice
    {
        public long RecordID { get; set; }
        public Nullable<System.DateTime> OrderedOn { get; set; }
        public string FSN { get; set; }
        public string Product { get; set; }
        public string OrderId { get; set; }
        public Nullable<long> ORDERITEMID { get; set; }
        public string SKUCode { get; set; }
        public Nullable<double> SellingPricePerItem { get; set; }
        public Nullable<long> ShippingChargeperitem { get; set; }
        public Nullable<long> OctroiFeeperitem { get; set; }
        public string EMIFeeperItem { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<double> Total { get; set; }
        public string BuyerName { get; set; }
        public string ShiptoName { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string PINCode { get; set; }
        public string TrackingID { get; set; }
        public Nullable<int> UserId { get; set; }
        public string OnlineType { get; set; }
        public Nullable<long> InvoiceID { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public string HASOFFER { get; set; }
        public Nullable<long> PRIMARYORDERITEMID { get; set; }
        public string OrderState { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<double> InvoiceAmount { get; set; }
        public Nullable<long> VATTotal { get; set; }
        public string ProcSLA { get; set; }
        public Nullable<System.DateTime> ConfirmedbyDate { get; set; }
        public Nullable<System.DateTime> ReadytoShipbydate { get; set; }
        public string Formrequirement { get; set; }
        public string Weightofshipment { get; set; }
        public string ShipmentStatus { get; set; }
        public string SellerBuyerInvoiceNo { get; set; }
        public string IMEI { get; set; }
        public string ReturnDisputeTickets { get; set; }
    }
}
