//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductManagementSystemData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPaymentVoucher
    {
        public tblPaymentVoucher()
        {
            this.tblPaymentToRefences = new HashSet<tblPaymentToRefence>();
            this.tblPaymentVoucherToLedgers = new HashSet<tblPaymentVoucherToLedger>();
        }
    
        public int PaymentVoucherID { get; set; }
        public string PaymentVoucherCode { get; set; }
        public Nullable<System.DateTime> PaymentVoucherDate { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public string Remark { get; set; }
        public Nullable<int> InsertBy { get; set; }
        public Nullable<System.DateTime> InsertAt { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public Nullable<int> PaymentTypeId { get; set; }
        public string PaymentFrom { get; set; }
        public Nullable<int> PartyID { get; set; }
        public Nullable<double> Kasar { get; set; }
    
        public virtual ICollection<tblPaymentToRefence> tblPaymentToRefences { get; set; }
        public virtual ICollection<tblPaymentVoucherToLedger> tblPaymentVoucherToLedgers { get; set; }
    }
}
