//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductManagementSystemData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPhone
    {
        public int PhoneID { get; set; }
        public Nullable<int> AddressID { get; set; }
        public string PhoneDescription { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<int> PartyID { get; set; }
        public Nullable<int> AddressIndex { get; set; }
        public Nullable<int> ModuleID { get; set; }
    }
}
