//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductManagementSystemData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblQuotationItem
    {
        public tblQuotationItem()
        {
            this.tblQuotItemsToDiscounts = new HashSet<tblQuotItemsToDiscount>();
            this.tblQuotItemsToTAXes = new HashSet<tblQuotItemsToTAX>();
        }
    
        public int RecordID { get; set; }
        public Nullable<int> QuotationID { get; set; }
        public Nullable<int> ItemTypeID { get; set; }
        public Nullable<int> ItemID { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<double> MRP { get; set; }
        public Nullable<int> Unit { get; set; }
        public Nullable<double> Rate { get; set; }
        public string Brand { get; set; }
        public string Remark { get; set; }
    
        public virtual tblQuotation tblQuotation { get; set; }
        public virtual ICollection<tblQuotItemsToDiscount> tblQuotItemsToDiscounts { get; set; }
        public virtual ICollection<tblQuotItemsToTAX> tblQuotItemsToTAXes { get; set; }
    }
}
