//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductManagementSystemData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblQuotation
    {
        public tblQuotation()
        {
            this.tblQuotationItems = new HashSet<tblQuotationItem>();
            this.tblQuotToDiscounts = new HashSet<tblQuotToDiscount>();
            this.tblQuotToTAXes = new HashSet<tblQuotToTAX>();
        }
    
        public int QuatationID { get; set; }
        public string QuatationCode { get; set; }
        public string Subject { get; set; }
        public Nullable<System.DateTime> QuationDate { get; set; }
        public Nullable<int> PartyID { get; set; }
        public string ContactPerson { get; set; }
        public Nullable<int> QuatationState { get; set; }
        public Nullable<int> TransportType { get; set; }
        public Nullable<int> TransportComany { get; set; }
        public string PaymentTerm { get; set; }
        public Nullable<System.DateTime> DeliveryTime { get; set; }
        public string OtherTerms { get; set; }
        public Nullable<int> InsertBy { get; set; }
        public Nullable<System.DateTime> InsertAt { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public Nullable<double> Total { get; set; }
    
        public virtual ICollection<tblQuotationItem> tblQuotationItems { get; set; }
        public virtual ICollection<tblQuotToDiscount> tblQuotToDiscounts { get; set; }
        public virtual ICollection<tblQuotToTAX> tblQuotToTAXes { get; set; }
    }
}
