//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductManagementSystemData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRejectionOutItem
    {
        public tblRejectionOutItem()
        {
            this.tblRejectionOutItemToDiscounts = new HashSet<tblRejectionOutItemToDiscount>();
        }
    
        public int RecordID { get; set; }
        public int RejectionOutID { get; set; }
        public int ItemID { get; set; }
        public double ActualQty { get; set; }
        public double BilledQty { get; set; }
        public int UnitID { get; set; }
        public double Rate { get; set; }
        public Nullable<int> GodownID { get; set; }
        public string BatchNo { get; set; }
        public string Remark { get; set; }
        public Nullable<int> InwardRefID { get; set; }
        public Nullable<int> PurchaseInvoiceID { get; set; }
        public Nullable<double> MRP { get; set; }
        public Nullable<int> ReferenceID { get; set; }
        public Nullable<int> ReferenceType { get; set; }
        public string TaxDescription { get; set; }
        public Nullable<int> TaxProfileID { get; set; }
        public Nullable<double> OGSPerValue { get; set; }
    
        public virtual tblRejectionOut tblRejectionOut { get; set; }
        public virtual ICollection<tblRejectionOutItemToDiscount> tblRejectionOutItemToDiscounts { get; set; }
    }
}
