//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductManagementSystemData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRejectionInItem
    {
        public int RecordID { get; set; }
        public Nullable<int> RejectionInID { get; set; }
        public Nullable<int> ItemID { get; set; }
        public Nullable<double> ActualQty { get; set; }
        public Nullable<double> BilledQty { get; set; }
        public Nullable<int> UnitID { get; set; }
        public Nullable<double> Rate { get; set; }
        public Nullable<int> GodownID { get; set; }
        public string BatchNo { get; set; }
        public string Remark { get; set; }
        public Nullable<int> OutwardRefID { get; set; }
        public Nullable<int> SalesInvoiceID { get; set; }
        public Nullable<double> MRP { get; set; }
        public Nullable<int> ReferenceID { get; set; }
        public Nullable<int> ReferenceType { get; set; }
        public string TaxDescription { get; set; }
        public Nullable<int> TaxProfileID { get; set; }
        public Nullable<double> OGSPerValue { get; set; }
    
        public virtual tblRejectionIn tblRejectionIn { get; set; }
    }
}
