//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductManagementSystemData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRejectionOut
    {
        public tblRejectionOut()
        {
            this.tblRejectionOutItems = new HashSet<tblRejectionOutItem>();
        }
    
        public int RejectionOutID { get; set; }
        public Nullable<System.DateTime> RejectionDate { get; set; }
        public string RejectionCode { get; set; }
        public string Subject { get; set; }
        public Nullable<int> PartyID { get; set; }
        public Nullable<int> InsertBy { get; set; }
        public Nullable<System.DateTime> InsertAt { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public Nullable<double> total { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<double> CashDisc { get; set; }
        public Nullable<int> TaxType { get; set; }
        public Nullable<double> CSTPerValue { get; set; }
        public Nullable<int> GodownID { get; set; }
        public string ReasonForEdit { get; set; }
        public Nullable<int> StateID { get; set; }
        public Nullable<int> TaxProfileCategoryID { get; set; }
        public Nullable<bool> IsTaxInclusive { get; set; }
        public Nullable<int> StoreID { get; set; }
        public Nullable<double> SumOfCostRate { get; set; }
    
        public virtual ICollection<tblRejectionOutItem> tblRejectionOutItems { get; set; }
    }
}
