//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductManagementSystemData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRequestToItem
    {
        public int RecordID { get; set; }
        public Nullable<int> ReqID { get; set; }
        public Nullable<int> ItemID { get; set; }
        public Nullable<short> ItemType { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<double> Rate { get; set; }
        public Nullable<int> Unit { get; set; }
        public Nullable<double> Discount { get; set; }
        public Nullable<double> VatPercentage { get; set; }
        public Nullable<double> CSTPercentage { get; set; }
        public string Remark_User { get; set; }
        public string Remark_supplier { get; set; }
    }
}
