//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductManagementSystemData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRequestMaster
    {
        public int RequestID { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public string ReqCode { get; set; }
        public string ReqSubject { get; set; }
        public Nullable<int> PartyID { get; set; }
        public Nullable<short> Stage { get; set; }
        public Nullable<double> DiscountPerctage { get; set; }
        public Nullable<double> VATPercentage { get; set; }
        public Nullable<double> CSTPercentage { get; set; }
        public string QuatetionValidity { get; set; }
        public string TransportMode { get; set; }
        public string PaymentTerms { get; set; }
        public string DeliveryTerms { get; set; }
        public string OtherRemark { get; set; }
    }
}
