//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductManagementSystemData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSalesOrderToTax
    {
        public int RecordID { get; set; }
        public int SalesOrderId { get; set; }
        public int TAXID { get; set; }
        public bool IsPercentage { get; set; }
        public double TAXValue { get; set; }
        public double NetValue { get; set; }
    
        public virtual tblSalesOrder tblSalesOrder { get; set; }
    }
}
