//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductManagementSystemData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSalesOrderItem
    {
        public tblSalesOrderItem()
        {
            this.tblSalesOrderItemToDiscounts = new HashSet<tblSalesOrderItemToDiscount>();
            this.tblSalesOrderItemToTAXes = new HashSet<tblSalesOrderItemToTAX>();
        }
    
        public int RecordID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<int> ItemTypeID { get; set; }
        public Nullable<int> ItemID { get; set; }
        public Nullable<double> ActualQty { get; set; }
        public Nullable<double> BilledQty { get; set; }
        public Nullable<int> Unit { get; set; }
        public Nullable<double> Rate { get; set; }
        public string Remark { get; set; }
        public Nullable<double> MRP { get; set; }
        public Nullable<int> GodownID { get; set; }
        public Nullable<int> TaxProfileID { get; set; }
        public string TaxDescription { get; set; }
    
        public virtual tblSalesOrder tblSalesOrder { get; set; }
        public virtual ICollection<tblSalesOrderItemToDiscount> tblSalesOrderItemToDiscounts { get; set; }
        public virtual ICollection<tblSalesOrderItemToTAX> tblSalesOrderItemToTAXes { get; set; }
    }
}
