//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductManagementSystemData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSalesInvoieToRedemption
    {
        public int RecordID { get; set; }
        public Nullable<int> InvoiceID { get; set; }
        public Nullable<int> RedemptionID { get; set; }
        public string Type { get; set; }
        public Nullable<double> TotalAmount { get; set; }
        public Nullable<double> RedemptionAmount { get; set; }
        public string RedemBy { get; set; }
        public Nullable<System.DateTime> RedemAt { get; set; }
    }
}
