//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductManagementSystemData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSalesOrder
    {
        public tblSalesOrder()
        {
            this.tblSalesOrderItems = new HashSet<tblSalesOrderItem>();
            this.tblSalesOrderToDiscounts = new HashSet<tblSalesOrderToDiscount>();
            this.tblSalesOrderToTaxes = new HashSet<tblSalesOrderToTax>();
        }
    
        public int SalesOrderID { get; set; }
        public string SalesOrderCode { get; set; }
        public string Subject { get; set; }
        public Nullable<int> PartyID { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string CustPONo { get; set; }
        public Nullable<System.DateTime> OrderValidityDate { get; set; }
        public Nullable<int> OrderStatus { get; set; }
        public Nullable<int> QuotRef { get; set; }
        public string PaymentTerms { get; set; }
        public string DeleveryTerm { get; set; }
        public string OtherTerms { get; set; }
        public string SenderParty { get; set; }
        public string RecieverParty { get; set; }
        public Nullable<int> TransportType { get; set; }
        public Nullable<int> TransportCompany { get; set; }
        public string DeliveryAddres { get; set; }
        public string LoadingPort { get; set; }
        public string DespatchPort { get; set; }
        public string CountryTo { get; set; }
        public string ContactPerson { get; set; }
        public Nullable<int> InsertBy { get; set; }
        public Nullable<System.DateTime> InsertAt { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public Nullable<double> total { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<double> RoundOff { get; set; }
        public Nullable<double> CashDisc { get; set; }
        public Nullable<int> GodownID { get; set; }
        public Nullable<int> TaxType { get; set; }
        public Nullable<double> CSTPerValue { get; set; }
        public string ReasonForEdit { get; set; }
        public Nullable<int> StateID { get; set; }
        public Nullable<int> TaxProfileCategoryID { get; set; }
        public Nullable<bool> IsTaxInclusive { get; set; }
    
        public virtual ICollection<tblSalesOrderItem> tblSalesOrderItems { get; set; }
        public virtual ICollection<tblSalesOrderToDiscount> tblSalesOrderToDiscounts { get; set; }
        public virtual ICollection<tblSalesOrderToTax> tblSalesOrderToTaxes { get; set; }
    }
}
