//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductManagementSystemData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSalesInvoicePayment
    {
        public int RecordID { get; set; }
        public Nullable<int> InvoiceID { get; set; }
        public Nullable<int> PartyID { get; set; }
        public string Remarks { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<bool> IsReconciliationDone { get; set; }
        public Nullable<int> ReconciliationBy { get; set; }
        public Nullable<System.DateTime> ReconciliationAt { get; set; }
        public string BankTransRefNo { get; set; }
        public string ReconciliationRemark { get; set; }
        public Nullable<int> InsertBy { get; set; }
        public Nullable<System.DateTime> InsertAt { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
    }
}
