//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductManagementSystemData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStockCountingCycleMaster
    {
        public tblStockCountingCycleMaster()
        {
            this.tblStockCountingVoucherMasters = new HashSet<tblStockCountingVoucherMaster>();
        }
    
        public int StockCountingCycleID { get; set; }
        public Nullable<int> StockCountingTypeID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string MoniteredBy { get; set; }
        public string CountingCode { get; set; }
        public Nullable<int> CompanyID { get; set; }
    
        public virtual tblStockCountingTypeMaster tblStockCountingTypeMaster { get; set; }
        public virtual ICollection<tblStockCountingVoucherMaster> tblStockCountingVoucherMasters { get; set; }
    }
}
