//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductManagementSystemData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSalesInvoiceToLedger
    {
        public int RecordID { get; set; }
        public int InvoiceID { get; set; }
        public int LedgerID { get; set; }
        public double Amount { get; set; }
        public bool IsCredit { get; set; }
        public string Remark { get; set; }
    
        public virtual tblParty_Master tblParty_Master { get; set; }
        public virtual tblSalesInvoice tblSalesInvoice { get; set; }
    }
}
