//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductManagementSystemData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblstatesuburb_Tbl
    {
        public int suburbid { get; set; }
        public string Suburb { get; set; }
        public string Statecode { get; set; }
        public string Suburbcode { get; set; }
        public string Countrycode { get; set; }
        public string Postcode { get; set; }
    }
}
