//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductManagementSystemData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStockCountingTypeMaster
    {
        public tblStockCountingTypeMaster()
        {
            this.tblStockCountingCycleMasters = new HashSet<tblStockCountingCycleMaster>();
        }
    
        public int StockCountingTypeID { get; set; }
        public string StockCountingTypeName { get; set; }
        public Nullable<int> CompanyID { get; set; }
    
        public virtual ICollection<tblStockCountingCycleMaster> tblStockCountingCycleMasters { get; set; }
    }
}
