//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductManagementSystemData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStockJournalToExpense
    {
        public int RecordId { get; set; }
        public Nullable<int> StockJrnId { get; set; }
        public Nullable<int> LedgerId { get; set; }
        public Nullable<bool> IsPercentage { get; set; }
        public Nullable<double> ExpenceValue { get; set; }
        public string Remark { get; set; }
    
        public virtual tblStockJournal tblStockJournal { get; set; }
    }
}
