//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductManagementSystemData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSalesInvoiceItem
    {
        public tblSalesInvoiceItem()
        {
            this.tblSalesInvoiceItemToDiscounts = new HashSet<tblSalesInvoiceItemToDiscount>();
            this.tblSalesInvoiceItemToTaxes = new HashSet<tblSalesInvoiceItemToTax>();
        }
    
        public int RecordID { get; set; }
        public Nullable<int> InvoiceID { get; set; }
        public Nullable<int> ItemID { get; set; }
        public Nullable<double> ActualQty { get; set; }
        public Nullable<double> BilledQty { get; set; }
        public Nullable<int> Unit { get; set; }
        public Nullable<double> Rate { get; set; }
        public Nullable<double> MRP { get; set; }
        public Nullable<int> GodownID { get; set; }
        public string Remark { get; set; }
        public Nullable<int> OutwardRef { get; set; }
        public Nullable<int> SORefNo { get; set; }
        public Nullable<int> OutRefNo { get; set; }
        public Nullable<System.DateTime> MfgDate { get; set; }
        public Nullable<System.DateTime> ExpDate { get; set; }
        public string TaxDescription { get; set; }
        public Nullable<int> FBInvoiceItemID { get; set; }
        public Nullable<int> FBInvoiceID { get; set; }
        public Nullable<double> SalesPrice { get; set; }
        public int TAXProfileID { get; set; }
        public Nullable<int> ReferenceID { get; set; }
        public Nullable<int> ReferenceTypeID { get; set; }
        public Nullable<double> OGSPerValue { get; set; }
    
        public virtual tblItemMaster tblItemMaster { get; set; }
        public virtual tblSalesInvoice tblSalesInvoice { get; set; }
        public virtual ICollection<tblSalesInvoiceItemToDiscount> tblSalesInvoiceItemToDiscounts { get; set; }
        public virtual ICollection<tblSalesInvoiceItemToTax> tblSalesInvoiceItemToTaxes { get; set; }
    }
}
