//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductManagementSystemData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTaxTypeMaster
    {
        public int TaxTypeId { get; set; }
        public string TaxTypeName { get; set; }
        public Nullable<bool> TaxType { get; set; }
        public Nullable<decimal> Value { get; set; }
        public Nullable<int> DutyAndTaxLedger { get; set; }
        public Nullable<int> CompanyID { get; set; }
    }
}
