//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductManagementSystemData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTaxProfileDetail
    {
        public int RecordID { get; set; }
        public Nullable<int> TaxProfileID { get; set; }
        public string ExpCode { get; set; }
        public string Title { get; set; }
        public string Formula { get; set; }
        public Nullable<int> LedgerID { get; set; }
        public Nullable<int> TaxID { get; set; }
        public Nullable<int> ReportID { get; set; }
        public Nullable<int> ReportColumnID { get; set; }
    }
}
