//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductManagementSystemData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTaxGroupToStateWiseTaxProfile
    {
        public int RecordID { get; set; }
        public Nullable<int> TAXGroupID { get; set; }
        public int TAXProfileID { get; set; }
        public Nullable<int> StateID { get; set; }
        public Nullable<int> TAXProfCatID { get; set; }
    }
}
