//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductManagementSystemData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUser
    {
        public tblUser()
        {
            this.tblUserPermissions = new HashSet<tblUserPermission>();
        }
    
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string Pwd { get; set; }
        public Nullable<int> QuestionID { get; set; }
        public string Answer { get; set; }
        public Nullable<int> UserTypeID { get; set; }
    
        public virtual ICollection<tblUserPermission> tblUserPermissions { get; set; }
    }
}
