//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductManagementSystemData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserPermission
    {
        public int PermissionID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> SectionID { get; set; }
        public Nullable<bool> isAdd { get; set; }
        public Nullable<bool> isEdit { get; set; }
        public Nullable<bool> isDelete { get; set; }
        public Nullable<bool> isView { get; set; }
    
        public virtual tblSectionMaster tblSectionMaster { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
