//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductManagementSystemData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWorkOrder
    {
        public int WorkOrderId { get; set; }
        public Nullable<int> CaptiUnitId { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string OrderCode { get; set; }
        public string OrderRemark { get; set; }
        public Nullable<System.DateTime> vilidTill { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> OwnerId { get; set; }
    }
}
