//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductManagementSystemData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWorkOrder_Items
    {
        public int RecordID { get; set; }
        public Nullable<int> WorkOrderId { get; set; }
        public Nullable<int> AssemblyId { get; set; }
        public Nullable<double> AssemblyLaberRate { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<int> Unit { get; set; }
    }
}
