//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductManagementSystemData
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMPStockJVItem
    {
        public int RecordID { get; set; }
        public Nullable<int> StockJournalID { get; set; }
        public Nullable<int> ItemID { get; set; }
        public Nullable<double> SystemQty { get; set; }
        public Nullable<double> BilledQty { get; set; }
        public Nullable<int> Unit { get; set; }
        public Nullable<double> Rate { get; set; }
        public Nullable<int> GodownID { get; set; }
        public string BatchNo { get; set; }
        public string Remark { get; set; }
        public Nullable<bool> IsCredit { get; set; }
    }
}
