//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductManagementSystemData
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempStockOrg
    {
        public Nullable<long> RecordID { get; set; }
        public string ItemName { get; set; }
        public string ItemCode { get; set; }
        public string Identifier { get; set; }
        public string BrandName { get; set; }
        public double OpeningQty { get; set; }
        public double TotalInQty { get; set; }
        public double TotalOutQty { get; set; }
        public double ClostingQty { get; set; }
        public int MinimumStock { get; set; }
        public string Distributor { get; set; }
        public int MaximumStock { get; set; }
    }
}
