//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductManagementSystemData
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempM1
    {
        public Nullable<double> RecordID { get; set; }
        public string ItemName { get; set; }
        public string ItemCode { get; set; }
        public string Identifier { get; set; }
        public Nullable<double> MRP { get; set; }
        public string BrandName { get; set; }
        public Nullable<double> PhysicalCount { get; set; }
        public string TypeofMerge { get; set; }
    }
}
