//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductManagementSystemData
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempStock
    {
        public int RecordID { get; set; }
        public string ItemName { get; set; }
        public string ItemCode { get; set; }
        public string Identifier { get; set; }
        public string BrandName { get; set; }
        public Nullable<int> OpeningQty { get; set; }
        public Nullable<double> TotalInQty { get; set; }
        public Nullable<double> TotalOutQty { get; set; }
        public Nullable<int> ClostingQty { get; set; }
        public Nullable<int> MinimumStock { get; set; }
        public string Distributor { get; set; }
        public Nullable<int> MaximumStock { get; set; }
    }
}
