//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductManagementSystemData
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempPurchaseInvoice_N
    {
        public Nullable<long> RowId { get; set; }
        public int TransTypeID { get; set; }
        public Nullable<int> RecordID { get; set; }
        public string TransactionType { get; set; }
        public int TransID { get; set; }
        public string TranCode { get; set; }
        public Nullable<System.DateTime> TranDate { get; set; }
        public Nullable<int> TranPartyID { get; set; }
        public Nullable<int> TranItemID { get; set; }
        public Nullable<double> TranActualQty { get; set; }
        public Nullable<double> TranBilledQty { get; set; }
        public Nullable<double> TransAmount { get; set; }
        public Nullable<int> TranUnitID { get; set; }
        public Nullable<double> TranRate { get; set; }
        public Nullable<double> TranMRP { get; set; }
        public Nullable<int> TranGodownID { get; set; }
        public Nullable<int> TranTAXProfileID { get; set; }
    }
}
