//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductManagementSystemData
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempStockCI
    {
        public int VoucherID { get; set; }
        public Nullable<int> StockCountingVoucherID { get; set; }
        public Nullable<int> ItemID { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<int> RackID { get; set; }
        public string Vat { get; set; }
        public Nullable<double> MRP { get; set; }
        public string Remark { get; set; }
        public string BarCodeID { get; set; }
    }
}
