//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductManagementSystemData
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempMergeStock1
    {
        public Nullable<int> aa { get; set; }
        public Nullable<int> RecordID { get; set; }
        public string ItemName { get; set; }
        public string F4 { get; set; }
        public string ItemCode { get; set; }
        public string Identifier { get; set; }
        public Nullable<double> MRP { get; set; }
        public string BrandName { get; set; }
        public Nullable<int> MinimumStock { get; set; }
        public string Distributor { get; set; }
        public Nullable<int> MaximumStock { get; set; }
        public Nullable<int> No_Transaction { get; set; }
        public Nullable<int> OpeningQty { get; set; }
        public Nullable<int> asTotaliNQty { get; set; }
        public Nullable<int> TotaloUTQty { get; set; }
        public Nullable<int> SysCount { get; set; }
        public Nullable<int> PhysicalCount { get; set; }
        public string TypeofMerge { get; set; }
    }
}
