//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductManagementSystemData
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempMerge1
    {
        public Nullable<double> aa { get; set; }
        public Nullable<double> RecordID { get; set; }
        public string ItemName { get; set; }
        public string F4 { get; set; }
        public string ItemCode { get; set; }
        public Nullable<double> Identifier { get; set; }
        public Nullable<double> MRP { get; set; }
        public string BrandName { get; set; }
        public Nullable<double> MinimumStock { get; set; }
        public string Distributor { get; set; }
        public Nullable<double> MaximumStock { get; set; }
        public Nullable<double> No_Transaction { get; set; }
        public Nullable<double> OpeningQty { get; set; }
        public Nullable<double> TotaliNQty { get; set; }
        public Nullable<double> TotaloUTQty { get; set; }
        public Nullable<double> SysCount { get; set; }
        public Nullable<double> PhysicalCount { get; set; }
        public string TypeofMerge { get; set; }
    }
}
