//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductManagementSystemData
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempCreditnote311014
    {
        public int CreidtNoteID { get; set; }
        public Nullable<System.DateTime> CreditNoteDate { get; set; }
        public string CrditNoteCode { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public string Remark { get; set; }
        public Nullable<int> InsertBy { get; set; }
        public Nullable<System.DateTime> InsertAt { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public Nullable<double> total { get; set; }
        public Nullable<int> PartyID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string InvoiceCode { get; set; }
        public Nullable<int> CNType { get; set; }
        public Nullable<int> PaidByPartyID { get; set; }
    }
}
