//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductManagementSystemData
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempStockj
    {
        public int StockJournalID { get; set; }
        public Nullable<int> StockJournalType { get; set; }
        public Nullable<int> StockCountingVoucherID { get; set; }
        public Nullable<System.DateTime> StkJrnllDate { get; set; }
        public string StkJrnlCode { get; set; }
        public string StkJrnlSubject { get; set; }
        public string stkJrnlRemark { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> InsertBy { get; set; }
        public Nullable<System.DateTime> InsertAt { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
    }
}
