//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductManagementSystemData
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempDelete9
    {
        public Nullable<long> RowID { get; set; }
        public string TransactionType { get; set; }
        public string TranCode { get; set; }
        public string TranDate { get; set; }
        public Nullable<System.DateTime> TranDate1 { get; set; }
        public int TranPartyID { get; set; }
        public string PartyName { get; set; }
        public int TranItemID { get; set; }
        public string ItemName { get; set; }
        public int BrandID { get; set; }
        public string BrandName { get; set; }
        public Nullable<double> OutQty { get; set; }
        public Nullable<double> INQty { get; set; }
        public double TranAmountOutQty { get; set; }
        public double TranAmountINQty { get; set; }
        public int TranUnitID { get; set; }
        public string UnitName { get; set; }
        public Nullable<double> TranRate { get; set; }
        public Nullable<double> TranMRP { get; set; }
        public int TranGodownID { get; set; }
        public string GodownName { get; set; }
        public int TranTAXProfileID { get; set; }
        public string ProfileName { get; set; }
        public Nullable<int> FinalQty { get; set; }
        public Nullable<double> FinalAmount { get; set; }
        public Nullable<double> ClosingStockVal { get; set; }
        public Nullable<double> OpeningStkVal { get; set; }
        public Nullable<int> ClosingStock { get; set; }
        public Nullable<int> OpeingStock { get; set; }
        public Nullable<int> ActuallQty { get; set; }
    }
}
